### ISSUE TITLE
运行文件找不到？

### ISSUE THREAD

**Issue by WuMrZore** [t123yh/simple-sandbox#16]
![image](https://user-images.githubusercontent.com/76389859/144806898-e4f1e1b3-bcf7-4996-9a19-d1b564ca4947.png)
请问为什么会在路径前面多一个@呢？这折磨我了好久了。

**Comment by WuMrZore** [comment]
发现这个问题是因为rootfs中并没有/bin/bash 这个文件导致的

**Comment by Menci** [comment]
@ 是错误信息的一部分，是 at 的意思 ……

**Comment by WuMrZore** [comment]
不过还是没解决我的问题，还是报文件查找不到
![image](https://user-images.githubusercontent.com/76389859/145031025-ee02b7bd-1281-42b1-a1ea-d660deb65513.png)
请问这是什么问题呢
