### ISSUE TITLE
'Operation not permitted'What's wrong with it?

### ISSUE THREAD

**Issue by daklqw** [t123yh/simple-sandbox#2]
I have ran 'chown -R $(whoami) ./' but it still cannot run
Error: `clone(ChildProcess, &*childStack.end(), CLONE_NEWNET | CLONE_NEWUTS | CLONE_NEWPID | CLONE_NEWNS | SIGCHLD, const_cast<void *>(reinterpret_cast<const void *>(&execParam)))`@../native/sandbox.cc,273: Operation not permitted

**Comment by t123yh** [comment]
You have to use root permission to run this sandbox.
BTW, you can optionally set the owner of rootfs to root(uid 0), so undesired modification to rootfs by the sandboxed program can be prevented.
