### ISSUE TITLE
请问能否提供一个从构建到引入模块使用的完整文档?

### ISSUE THREAD

**Issue by ShirasawaSama** [t123yh/simple-sandbox#7]
本人尝试了许多方法，依次出现了 #1 和 #2 中的问题，并按照其中作者的回复进行修改，但仍旧如 #1 所示。

同时 README 中的说明好像也不是很完善。

以及 `interfaces.ts` 文件中的 `interface SandboxParameter` 的 `user` 属性应不为可选属性。

如果作者您可以提供一个完整的文档，我将感激涕零。谢谢作者！

## 版本

- **Node.js**: v15.4.0
- **系统**: Debian GNU/Linux bullseye/sid

**Comment by Menci** [comment]
可以看看 demo

**Comment by t123yh** [comment]
经调试，是因为 `npx ts-node` 的问题，直接使用 `node demo.js` 就行了
